Added Shattering Bellow (257732) to BoralusTrash.lua
DeadlyBossMods/DBM-Dungeons pull request #262
Opened 2024-09-19 16:51 UTC by linaori

Haven't tested the change locally in Siege of Boralus yet, only if the options loaded properly.
![image](https://github.com/user-attachments/assets/53ae2896-f4d6-432c-9ee9-ed7b81ce5c94)

2024-09-19 17:05 UTC, MysticalOS requested changes
self.Options.SpecWarn257732cast is unneeded unless you're using it as a fallback condition to a secondary alert (like some prio interrupts do)

basically, the Show object already calls bool, but the interrupt options manually call it so they can go to "else" condition if option is off if that makes sense.

2024-09-19 17:40 UTC, linaori commented
I've removed the check and verified it's working correctly in Boralus. I'll just have to verify that it's indeed Mythic only

2024-09-19 18:33 UTC, linaori commented
@MysticalOS I've confirmed it also works in the heroic version. In normal it also casts but there's no "stop casting". It's re-using the Freehold mob+cast and that's triggering `local warnShatteringBellow = mod:NewCastAnnounce(257732, 4)` from Freehold trash. Not sure what they did here but it seems to work on the difficulties it matters most.

2024-09-20 06:55 UTC, MysticalOS approved these changes

2024-09-20 06:55 UTC, merged